# Generated by Django 6.0 on 2025-12-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_phone', models.BooleanField(default=False, help_text='Require phone number when creating customers', verbose_name='Require Phone')),
                ('require_email', models.BooleanField(default=False, help_text='Require email when creating customers', verbose_name='Require Email')),
                ('require_tax_id', models.BooleanField(default=False, help_text='Require tax ID when creating customers', verbose_name='Require Tax ID')),
                ('show_inactive', models.BooleanField(default=False, help_text='Show inactive customers in the list by default', verbose_name='Show Inactive Customers')),
                ('default_sort', models.CharField(choices=[('name', 'Name'), ('-created_at', 'Newest first'), ('-total_spent', 'Highest spending'), ('-visit_count', 'Most visits')], default='name', max_length=20, verbose_name='Default Sort')),
                ('include_stats_in_export', models.BooleanField(default=True, help_text='Include spending statistics in CSV exports', verbose_name='Include Stats in Export')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customers Configuration',
                'verbose_name_plural': 'Customers Configuration',
            },
        ),
    ]
